<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.Workspace" Version="15.1.1--ci.8" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql" />
    <None Remove="Res\**\*.sql" />
    <None Remove="Res\**\*.tql" />
  </ItemGroup>
</Project>